# Spaces not tabs in this file...
#
# Site settings
title: ICASS Demo
organization: ICASS Service Center, U.S. Department of State
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    The International Cooperative Administrative Support Services (ICASS) 
    system is the principal means by which the U.S. Government provides and 
    shares the cost of common administrative support at its more than 250 
    diplomatic and consular posts overseas.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://j-mccombs.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
